const app=document.querySelector('#app'),toastEl=document.querySelector('#toast');
const categories=[['🔧','Ремонт','2 410'],['🧹','Уборка','1 280'],['🚚','Перевозки','870'],['💻','IT и дизайн','3 540'],['📚','Обучение','2 130'],['🐾','Животные','940'],['💅','Красота','1 760'],['📸','Фото и видео','640'],['🌿','Сад и дача','720'],['⚖️','Юристы','580'],['🎉','Мероприятия','430'],['➕','Все услуги','14 800']];
const seed=[
{id:1,icon:'🔧',title:'Мастер на час',cat:'Ремонт',name:'Алексей Морозов',rating:4.9,reviews:128,price:'от 1 500 ₽',city:'Москва',verified:true,selfEmployed:true,pro:true,distance:1.2,response:'5 минут',desc:'Сборка мебели, электрика и мелкий бытовой ремонт.',online:true,lat:55.766,lng:37.621},
{id:2,icon:'🧹',title:'Уборка квартиры',cat:'Уборка',name:'Clean Pro',rating:4.8,reviews:94,price:'от 2 300 ₽',city:'Москва',verified:true,company:true,pro:true,distance:2.4,response:'10 минут',desc:'Поддерживающая и генеральная уборка с материалами.',online:true,lat:55.751,lng:37.607},
{id:3,icon:'💻',title:'Сайт и фирменный стиль',cat:'IT и дизайн',name:'Мария К.',rating:5.0,reviews:67,price:'от 12 000 ₽',city:'Онлайн',verified:true,selfEmployed:true,pro:true,distance:null,response:'30 минут',desc:'Дизайн, лендинги и упаковка бизнеса под ключ.',online:false,lat:55.744,lng:37.648},
{id:4,icon:'🚚',title:'Грузовое такси',cat:'Перевозки',name:'Иван Петров',rating:4.7,reviews:211,price:'от 900 ₽/ч',city:'Москва',verified:true,ip:true,distance:3.1,response:'15 минут',desc:'Газель, грузчики, квартирные и офисные переезды.',online:true,lat:55.78,lng:37.59},
{id:5,icon:'📚',title:'Репетитор по математике',cat:'Обучение',name:'Ольга Смирнова',rating:4.9,reviews:83,price:'от 1 200 ₽',city:'Онлайн',verified:true,selfEmployed:true,distance:null,response:'1 час',desc:'Подготовка к ОГЭ и ЕГЭ, понятное объяснение.',online:false,lat:55.735,lng:37.618},
{id:6,icon:'🐾',title:'Выгул и передержка собак',cat:'Животные',name:'Анна Лебедева',rating:5.0,reviews:44,price:'от 700 ₽',city:'Москва',verified:true,selfEmployed:true,distance:.8,response:'5 минут',desc:'Бережный уход, фотоотчёт и прогулки по графику.',online:true,lat:55.757,lng:37.642},
{id:7,icon:'💅',title:'Маникюр с выездом',cat:'Красота',name:'Диана',rating:4.9,reviews:76,price:'от 1 900 ₽',city:'Москва',verified:true,selfEmployed:true,distance:4.2,response:'20 минут',desc:'Стерильные инструменты, большая палитра и выезд.',online:true,lat:55.72,lng:37.61},
{id:8,icon:'📸',title:'Семейная фотосессия',cat:'Фото и видео',name:'Роман С.',rating:4.8,reviews:52,price:'от 6 000 ₽',city:'Москва',verified:true,selfEmployed:true,distance:2.8,response:'40 минут',desc:'Живые кадры, помощь с образами, готовность 7 дней.',online:false,lat:55.79,lng:37.64}
];
const store=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
let state={page:'home',filter:'Все',query:'',createMode:'task',view:'list',role:store('pm_role','customer'),fav:store('pm_fav',[]),services:store('pm_services',seed),tasks:store('pm_tasks',[]),messages:store('pm_messages',[]),user:store('pm_user',{name:'Светлана',city:'Москва',verified:false})};
const save=()=>{localStorage.setItem('pm_role',JSON.stringify(state.role));localStorage.setItem('pm_fav',JSON.stringify(state.fav));localStorage.setItem('pm_services',JSON.stringify(state.services));localStorage.setItem('pm_tasks',JSON.stringify(state.tasks));localStorage.setItem('pm_messages',JSON.stringify(state.messages));localStorage.setItem('pm_user',JSON.stringify(state.user))};
function toast(t){toastEl.textContent=t;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1900)}
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function nav(){return `<nav class="nav">${[['home','⌂','Главная'],['catalog','⌕','Поиск'],['create','＋','Создать'],['chats','✉','Чаты'],['profile','☻','Профиль']].map(x=>`<button class="${state.page===x[0]?'active':''}" onclick="go('${x[0]}')"><i>${x[1]}</i>${x[2]}</button>`).join('')}</nav>`}
function shell(content){app.innerHTML=`<div class="app"><header class="topbar"><div class="topin"><div class="brand" onclick="go('home')"><div class="brandmark">🤝</div><span>Помогай</span><small class="brandtag">Нужна помощь? Помогай.</small></div><label class="searchbox">⌕<input id="q" aria-label="Поиск" placeholder="Услуга, специалист или задача" value="${escapeHtml(state.query)}"></label><button class="iconbtn" onclick="toast('Новых уведомлений нет')">♢</button><div class="avatar" onclick="go('profile')">${escapeHtml(state.user.name[0]||'П')}</div></div></header><main class="main">${content}</main>${nav()}</div>`;document.querySelector('#q')?.addEventListener('input',e=>{state.query=e.target.value;if(['home','catalog'].includes(state.page))render()})}
function filtered(){let a=[...state.services];if(state.filter!=='Все')a=a.filter(x=>x.cat===state.filter);if(state.query.trim()){const q=state.query.toLowerCase();a=a.filter(x=>(x.title+x.cat+x.name+x.desc+x.city).toLowerCase().includes(q))}return a.sort((a,b)=>(b.pro-a.pro)||(a.distance??99)-(b.distance??99)||b.rating-a.rating)}
function badges(s){return `${s.pro?'<span class="badge pro">PRO</span>':''}${s.verified?'<span class="badge verifiedBadge">✓ Проверен</span>':''}${s.selfEmployed?'<span class="badge neutral">Самозанятый</span>':''}${s.ip?'<span class="badge neutral">ИП</span>':''}${s.company?'<span class="badge neutral">Компания</span>':''}`}
function cards(items){if(!items.length)return `<div class="empty panel">Ничего не найдено. Попробуйте другой запрос или категорию.</div>`;return `<div class="grid">${items.map(s=>`<article class="card"><div class="cover">${s.icon}<button class="favbtn" aria-label="Избранное" onclick="event.stopPropagation();fav(${s.id})">${state.fav.includes(s.id)?'♥':'♡'}</button></div><div class="cardbody"><div class="badges">${badges(s)}</div><span class="rating">★ ${s.rating} · ${s.reviews}</span><h3>${escapeHtml(s.title)}</h3><div class="muted">${escapeHtml(s.name)} · ${escapeHtml(s.city)}</div><div class="micro">${s.distance!=null?`📍 ${s.distance} км · `:''}⚡ Ответит за ${escapeHtml(s.response)}</div><p class="muted desc">${escapeHtml(s.desc)}</p><div class="row"><span class="price">${escapeHtml(s.price)}</span><button class="btn soft" onclick="openService(${s.id})">Подробнее</button></div></div></article>`).join('')}</div>`}
function home(){shell(`<section class="hero"><div><span class="eyebrow">Нужна помощь? Помогай.</span><h1>Помощь рядом с вами</h1><p>Найдите человека для задачи или предложите свою помощь. Для дома, бизнеса и повседневных дел.</p></div><div class="heroVisual"><div class="visualCard"><div class="big">🤝</div><b>Люди помогают людям</b><small>Проверенные помощники рядом</small></div></div></section><div class="choiceGrid"><button class="choiceCard help" onclick="go('catalog')"><span class="choiceIcon">⌕</span><b>Найти помощь</b><span>Специалисты и помощники рядом с вами</span></button><button class="choiceCard give" onclick="chooseRole('helper')"><span class="choiceIcon">🤝</span><b>Начать помогать</b><span>Создайте профиль и предложите свои услуги</span></button></div><div class="trust"><div class="trustItem"><i>🛡️</i><div><b>Проверенные профили</b><span class="muted">Документы и статусы</span></div></div><div class="trustItem"><i>💬</i><div><b>Безопасное общение</b><span class="muted">Чат внутри сервиса</span></div></div><div class="trustItem"><i>⚡</i><div><b>Быстрые отклики</b><span class="muted">В среднем за 15 минут</span></div></div></div><section class="section"><div class="sectionHead"><div><h2>Популярные категории</h2><div class="muted">Выберите, что нужно сделать</div></div></div><div class="cats">${categories.map(c=>`<div class="cat" onclick="setFilter('${c[1]==='Все услуги'?'Все':c[1]}')"><div class="ico">${c[0]}</div><b>${c[1]}</b><span>${c[2]} специалистов</span></div>`).join('')}</div></section><section class="section"><div class="sectionHead"><div><h2>Помощь рядом</h2><div class="muted">Высокий рейтинг и быстрый ответ</div></div><button class="btn outline" onclick="go('catalog')">Смотреть все</button></div>${cards(filtered().slice(0,6))}</section><section class="section proBanner"><div><h2>Помогай PRO</h2><p>Бейдж PRO, приоритет в поиске, больше откликов и расширенная статистика.</p></div><button class="btn primary" onclick="showPro()">от 399 ₽ / месяц</button></section>`)}
function catalog(){const items=filtered();shell(`<section><div class="sectionHead"><div><h2>Специалисты и услуги</h2><div class="muted">${items.length} предложений</div></div><div class="viewSwitch"><button class="chip ${state.view==='list'?'active':''}" onclick="state.view='list';render()">Список</button><button class="chip ${state.view==='map'?'active':''}" onclick="state.view='map';render()">Карта</button><button class="btn outline" onclick="showFilters()">⚙ Фильтры</button></div></div><div class="chips">${['Все',...categories.slice(0,-1).map(x=>x[1])].map(x=>`<button class="chip ${state.filter===x?'active':''}" onclick="setFilter('${x}')">${x}</button>`).join('')}</div></section><section class="section">${state.view==='map'?mapView(items):cards(items)}</section>`)}
function mapView(items){return `<div class="mapWrap"><div class="mapCanvas">${items.filter(x=>x.lat).map((s,i)=>`<button class="mapPin" style="left:${18+(i*11)%70}%;top:${18+(i*17)%62}%" onclick="openService(${s.id})">${s.icon}<span>${escapeHtml(s.price)}</span></button>`).join('')}<div class="mapCenter">Вы здесь</div></div><div class="mapList">${items.slice(0,4).map(s=>`<div class="listItem" onclick="openService(${s.id})"><div class="thumb">${s.icon}</div><div><b>${escapeHtml(s.title)}</b><div class="muted">${s.distance??'онлайн'} ${s.distance!=null?'км':''} · ${escapeHtml(s.price)}</div></div><div class="spacer"></div>›</div>`).join('')}</div></div>`}
function create(){shell(`<section class="panel"><div class="sectionHead"><div><h2>Новое размещение</h2><div class="muted">Опишите задачу или предложите услугу</div></div></div><div class="seg"><button class="${state.createMode==='task'?'active':''}" onclick="state.createMode='task';render()">Задача</button><button class="${state.createMode==='service'?'active':''}" onclick="state.createMode='service';render()">Услуга</button></div><div style="margin-top:18px">${state.createMode==='task'?taskFields():serviceFields()}</div></section><section class="section"><div class="sectionHead"><h2>Мои публикации</h2><span class="muted">${state.tasks.length}</span></div><div class="list">${state.tasks.length?state.tasks.map(t=>`<div class="listItem"><div class="thumb">📋</div><div><b>${escapeHtml(t.title)}</b><div class="muted">${escapeHtml(t.budget)} · ${escapeHtml(t.city)}</div></div><div class="spacer"></div><span class="status">Опубликовано</span></div>`).join(''):'<div class="empty panel">Публикаций пока нет</div>'}</div></section>`)}
function taskFields(){return `<form class="form" onsubmit="addTask(event)"><div class="field"><label>Что нужно сделать?</label><input name="title" required placeholder="Например, собрать шкаф"></div><div class="field"><label>Категория</label><select name="cat">${categories.slice(0,-1).map(x=>`<option>${x[1]}</option>`).join('')}</select></div><div class="field"><label>Описание</label><textarea name="desc" required placeholder="Добавьте детали, сроки и пожелания"></textarea></div><div class="field"><label>Адрес</label><input name="city" required value="Москва"></div><div class="field"><label>Дата и время</label><input name="date" type="datetime-local"></div><div class="field"><label>Бюджет</label><input name="budget" required placeholder="Например, до 5 000 ₽"></div><div class="field"><label>Фотографии</label><input type="file" accept="image/*" multiple></div><button class="btn primary">Опубликовать задачу</button></form>`}
function serviceFields(){return `<form class="form" onsubmit="addService(event)"><div class="field"><label>Название услуги</label><input name="title" required placeholder="Например, ремонт стиральных машин"></div><div class="field"><label>Категория</label><select name="cat">${categories.slice(0,-1).map(x=>`<option>${x[1]}</option>`).join('')}</select></div><div class="field"><label>Описание</label><textarea name="desc" required placeholder="Расскажите об опыте и условиях"></textarea></div><div class="field"><label>Цена</label><input name="price" required placeholder="от 1 000 ₽"></div><div class="field"><label>Статус</label><select name="legal"><option>Самозанятый</option><option>ИП</option><option>Компания</option><option>Частное лицо</option></select></div><div class="field"><label>Фотографии работ</label><input type="file" accept="image/*" multiple></div><button class="btn primary">Разместить услугу</button></form>`}
function chats(){shell(`<section><div class="sectionHead"><div><h2>Сообщения</h2><div class="muted">Все договорённости в одном месте</div></div></div><div class="notice">Чат работает локально в демо-режиме. После добавления ключей Supabase он может быть подключён к Realtime.</div><div class="list" style="margin-top:14px">${state.messages.length?state.messages.map((m,i)=>`<div class="listItem" onclick="chat(${i})"><div class="thumb">💬</div><div><b>${escapeHtml(m.name)}</b><div class="muted">${escapeHtml(m.items.at(-1)?.text||'Начните диалог')}</div></div><div class="spacer"></div><span>›</span></div>`).join(''):'<div class="empty panel">Нет переписок. Откройте услугу и напишите специалисту.</div>'}</div></section>`)}
function profile(){const f=state.services.filter(x=>state.fav.includes(x.id));shell(`<section class="panel"><div class="row"><div><h2>${escapeHtml(state.user.name)}</h2><div class="muted">${state.role==='helper'?'Помощник':'Заказчик'} · ${escapeHtml(state.user.city)}</div><div class="badges" style="margin-top:8px">${state.user.verified?'<span class="badge verifiedBadge">✓ Профиль подтверждён</span>':'<span class="badge neutral">Профиль не подтверждён</span>'}</div></div><div class="avatar" style="width:70px;height:70px;font-size:25px">${escapeHtml(state.user.name[0]||'П')}</div></div><div class="stats"><div class="stat"><b>${state.tasks.length}</b><span class="muted">публикаций</span></div><div class="stat"><b>${f.length}</b><span class="muted">в избранном</span></div><div class="stat"><b>4,9</b><span class="muted">рейтинг</span></div></div><div class="actions"><button class="btn soft" onclick="editProfile()">Редактировать</button><button class="btn outline" onclick="chooseRole()">Сменить роль</button><button class="btn outline" onclick="installHelp()">Установить</button></div></section><section class="section panel"><h2>Безопасность</h2><div class="list" style="margin-top:14px"><div class="listItem" onclick="verifyProfile()"><div class="thumb">🛡️</div><div><b>Подтвердить профиль</b><div class="muted">Документ, самозанятость или ИП</div></div><div class="spacer"></div>›</div><div class="listItem" onclick="showLegal('privacy')"><div class="thumb">🔒</div><div><b>Конфиденциальность</b><div class="muted">Как используются данные</div></div><div class="spacer"></div>›</div><div class="listItem" onclick="showLegal('terms')"><div class="thumb">📄</div><div><b>Правила сервиса</b><div class="muted">Условия использования</div></div><div class="spacer"></div>›</div></div></section><section class="section"><div class="sectionHead"><h2>Избранное</h2><span class="muted">${f.length}</span></div>${cards(f)}</section><section class="section proBanner"><div><h2>Помогай PRO</h2><p>Приоритет, бейдж и статистика просмотров.</p></div><button class="btn primary" onclick="showPro()">Подключить</button></section>`)}
function setFilter(x){state.filter=x;state.page='catalog';render()} function go(p){state.page=p;window.scrollTo(0,0);render()}
function fav(id){state.fav=state.fav.includes(id)?state.fav.filter(x=>x!==id):[...state.fav,id];save();render();toast('Избранное обновлено')}
function addTask(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target));state.tasks.unshift({...d,id:Date.now()});save();e.target.reset();render();toast('Задание опубликовано')}
function addService(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.target)),icon=(categories.find(x=>x[1]===d.cat)||['✨'])[0];state.services.unshift({...d,id:Date.now(),icon,name:state.user.name,rating:5,reviews:0,city:state.user.city,verified:state.user.verified,selfEmployed:d.legal==='Самозанятый',ip:d.legal==='ИП',company:d.legal==='Компания',distance:1.5,response:'15 минут',online:true});save();state.page='catalog';render();toast('Услуга опубликована')}
function modal(html){document.body.insertAdjacentHTML('beforeend',`<div class="modalwrap" id="modal" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="sheetbar"></div>${html}</div></div>`)} function closeModal(){document.querySelector('#modal')?.remove()}
function openService(id){const s=state.services.find(x=>x.id===id);modal(`<div class="cover" style="border-radius:22px">${s.icon}</div><div class="sectionHead" style="margin-top:16px"><div><h2>${escapeHtml(s.title)}</h2><div class="muted">${escapeHtml(s.name)}</div><div class="badges">${badges(s)}</div></div><b class="price">${escapeHtml(s.price)}</b></div><span class="rating">★ ${s.rating} · ${s.reviews} отзывов</span><p>${escapeHtml(s.desc)}</p><div class="panel"><b>${s.online?'● Сейчас онлайн':`Обычно отвечает за ${escapeHtml(s.response)}`}</b><div class="muted">${escapeHtml(s.city)}${s.distance!=null?` · ${s.distance} км`:''} · На сервисе более года</div></div><div class="actions"><button class="btn primary" onclick="startChat(${s.id})">Написать</button><button class="btn outline" onclick="fav(${s.id})">${state.fav.includes(s.id)?'Убрать из избранного':'В избранное'}</button><button class="btn outline" onclick="reportUser(${s.id})">Пожаловаться</button></div>`)}
function startChat(id){const s=state.services.find(x=>x.id===id);let i=state.messages.findIndex(x=>x.serviceId===id);if(i<0){state.messages.push({serviceId:id,name:s.name,items:[{from:'them',text:'Здравствуйте! Расскажите, пожалуйста, подробнее о задаче.'}]});i=state.messages.length-1;save()}closeModal();chat(i)}
function chat(i){const c=state.messages[i];closeModal();modal(`<div class="row"><div><h2 style="margin:0">${escapeHtml(c.name)}</h2><div class="muted">Обычно отвечает быстро</div></div><button class="btn outline" onclick="closeModal()">Закрыть</button></div><div class="chat">${c.items.map(x=>`<div class="msg ${x.from==='me'?'me':''}">${escapeHtml(x.text)}</div>`).join('')}</div><form class="row" onsubmit="sendMsg(event,${i})"><input name="text" required placeholder="Сообщение" style="flex:1;border:1px solid var(--line);border-radius:14px;padding:13px"><button class="btn primary">Отправить</button></form>`)}
function sendMsg(e,i){e.preventDefault();const t=new FormData(e.target).get('text');state.messages[i].items.push({from:'me',text:t});save();chat(i);setTimeout(()=>{state.messages[i].items.push({from:'them',text:'Спасибо! Напишите удобный день и время.'});save();chat(i)},700)}
function chooseRole(role){modal(`<h2>Как вы хотите использовать Помогай?</h2><div class="roleGrid"><button class="roleCard" onclick="setRole('customer')"><b>Мне нужна помощь</b><span>Размещать задачи и выбирать исполнителей</span></button><button class="roleCard" onclick="setRole('helper')"><b>Хочу помогать</b><span>Предлагать услуги и получать заказы</span></button></div>`);if(role==='helper')setTimeout(()=>{},0)}
function setRole(r){state.role=r;state.createMode=r==='helper'?'service':'task';save();closeModal();go(r==='helper'?'create':'home');toast(r==='helper'?'Режим помощника включён':'Режим заказчика включён')}
function editProfile(){modal(`<h2>Редактирование профиля</h2><form class="form" onsubmit="saveProfile(event)"><div class="field"><label>Имя</label><input name="name" required value="${escapeHtml(state.user.name)}"></div><div class="field"><label>Город</label><input name="city" required value="${escapeHtml(state.user.city)}"></div><button class="btn primary">Сохранить</button></form>`)}
function saveProfile(e){e.preventDefault();state.user={...state.user,...Object.fromEntries(new FormData(e.target))};save();closeModal();render();toast('Профиль обновлён')}
function verifyProfile(){modal(`<h2>Подтверждение профиля</h2><p class="muted">Загрузите документ или подтвердите статус через подключённого провайдера. В демо данные не отправляются.</p><div class="field"><label>Тип подтверждения</label><select><option>Паспорт</option><option>Самозанятый</option><option>ИП / Компания</option></select></div><div class="field" style="margin-top:12px"><label>Документ</label><input type="file" accept="image/*,.pdf"></div><button class="btn primary" style="margin-top:16px" onclick="state.user.verified=true;save();closeModal();render();toast('Демо-профиль подтверждён')">Отправить на проверку</button>`)}
function showFilters(){modal(`<h2>Фильтры</h2><div class="form"><div class="field"><label>Расстояние</label><select><option>До 2 км</option><option>До 5 км</option><option>До 10 км</option><option>Онлайн</option></select></div><div class="field"><label>Статус</label><select><option>Все</option><option>Только проверенные</option><option>Самозанятые</option><option>ИП и компании</option></select></div><div class="field"><label>Сортировка</label><select><option>Рекомендуемые</option><option>Ближе ко мне</option><option>По рейтингу</option><option>Сначала дешевле</option></select></div><button class="btn primary" onclick="closeModal();toast('Фильтры применены')">Применить</button></div>`)}
function showPro(){modal(`<h2>Помогай PRO</h2><div class="proFeatures"><div>🏅 Бейдж PRO</div><div>🚀 Приоритет в поиске</div><div>💬 Больше откликов</div><div>📊 Расширенная статистика</div></div><div class="panel"><b class="price">399 ₽ / месяц</b><p class="muted">Подключение платежей выполняется через серверный платёжный провайдер.</p></div><button class="btn primary" onclick="toast('Для оплаты нужно подключить ЮKassa/CloudPayments')">Подключить PRO</button>`)}
function reportUser(){modal(`<h2>Жалоба</h2><form class="form" onsubmit="event.preventDefault();closeModal();toast('Жалоба отправлена модератору')"><div class="field"><label>Причина</label><select><option>Мошенничество</option><option>Неверная информация</option><option>Спам</option><option>Другое</option></select></div><div class="field"><label>Комментарий</label><textarea></textarea></div><button class="btn danger">Отправить жалобу</button></form>`)}
function installHelp(){toast('Safari → Поделиться → На экран «Домой»')}
function showLegal(type){const privacy=`<h2>Конфиденциальность</h2><p>Демо хранит данные в браузере. Для запуска предусмотрены Supabase Auth, RLS, защищённое хранилище и удаление аккаунта.</p>`;const terms=`<h2>Правила сервиса</h2><p>Размещайте достоверные объявления, общайтесь внутри сервиса и сообщайте о подозрительных действиях. Платежи и проверка документов должны проводиться через подключённых провайдеров.</p>`;modal(`${type==='privacy'?privacy:terms}<button class="btn outline" onclick="closeModal()">Закрыть</button>`)}
function render(){({home,catalog,create,chats,profile}[state.page]||home)()} Object.assign(window,{go,setFilter,fav,openService,addTask,addService,startChat,chat,sendMsg,closeModal,installHelp,showLegal,state,render,chooseRole,setRole,editProfile,saveProfile,verifyProfile,showFilters,showPro,reportUser});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
