const app=document.querySelector('#app');
const toastEl=document.querySelector('#toast');

const categories=[
  {id:'home',title:'Дом и ремонт',mark:'ДР',description:'Мастера для квартиры, дома и техники',subs:['Сантехник','Электрик','Сборка мебели','Ремонт техники','Отделочные работы','Мелкий бытовой ремонт','Установка дверей','Ремонт окон','Умный дом']},
  {id:'cleaning',title:'Уборка',mark:'УБ',description:'Поддерживающая и генеральная уборка',subs:['Уборка квартиры','Мытьё окон','Химчистка мебели','Уборка после ремонта','Уборка офиса','Глажка белья','Уход за гардеробом']},
  {id:'delivery',title:'Курьеры и перевозки',mark:'КП',description:'Доставка, переезды и грузовая помощь',subs:['Курьер','Переезд','Грузчики','Перевозка мебели','Доставка продуктов','Междугородняя доставка','Услуги водителя']},
  {id:'digital',title:'IT и цифровые услуги',mark:'IT',description:'Техника, сайты, дизайн и настройка',subs:['Компьютерная помощь','Разработка сайтов','Дизайн','Настройка телефона','Фото и видео','Продвижение','Кибербезопасность','Настройка умного дома','Работа с данными']},
  {id:'education',title:'Обучение',mark:'ОБ',description:'Репетиторы и практические навыки',subs:['Школьные предметы','Иностранные языки','Музыка','Подготовка к экзаменам','Компьютерная грамотность','Дошкольная подготовка','Профессиональные навыки']},
  {id:'legal',title:'Юристы',mark:'ЮР',description:'Консультации по направлениям права',subs:['Семейное право','Жилищное право','Трудовое право','Защита потребителей','Наследство','Налоги и бизнес','Автоюрист']},
  {id:'pets',title:'Животные',mark:'ЖИ',description:'Забота о питомцах рядом с домом',subs:['Выгул собак','Передержка','Груминг','Зооняня','Дрессировка']},
  {id:'care',title:'Уход и сопровождение',mark:'УС',description:'Помощь детям, взрослым и пожилым',subs:['Няня','Сопровождение пожилых','Помощь по дому','Сопровождение на прогулке','Сиделка без медуслуг']},
  {id:'beauty',title:'Красота и стиль',mark:'КС',description:'Услуги мастеров с выездом и в студии',subs:['Парикмахер','Маникюр','Макияж','Стилист','Массаж без лечения']},
  {id:'events',title:'Праздники и события',mark:'ПС',description:'Организация, съёмка и оформление',subs:['Фотограф','Видеограф','Ведущий','Декоратор','Музыкант']},
  {id:'business',title:'Бизнес-помощь',mark:'БП',description:'Документы, учёт и деловые задачи',subs:['Бухгалтер','Помощь с документами','Переводчик','Ассистент','Подбор персонала']},
  {id:'auto',title:'Авто',mark:'АВ',description:'Помощь с автомобилем и перевозкой',subs:['Автоэлектрик','Диагностика','Шиномонтаж','Помощь на дороге','Подбор автомобиля','Автомойка и детейлинг','Перегон автомобиля']},
  {id:'garden',title:'Дача и участок',mark:'ДУ',description:'Уход за участком, садом и постройками',subs:['Уход за садом','Стрижка газона','Посадка растений','Уборка участка','Ремонт теплиц','Колодцы и водоснабжение','Сезонная подготовка']},
  {id:'food',title:'Еда и кулинария',mark:'ЕК',description:'Домашняя еда, заготовки и помощь на кухне',subs:['Домашний повар','Выпечка и десерты','Заготовки','Праздничное меню','Доставка домашней еды','Помощь на кухне']},
  {id:'sport',title:'Спорт и активность',mark:'СА',description:'Тренировки и активный досуг',subs:['Фитнес','Йога','Бег','Плавание','Танцы','Шахматы','Тренировки на улице']},
  {id:'creative',title:'Творчество и хобби',mark:'ТХ',description:'Рукоделие, искусство и занятия для души',subs:['Рисование','Керамика','Шитьё','Вязание','Столярное дело','Вокал','Творческие мастер-классы']},
  {id:'documents',title:'Документы и переводы',mark:'ДП',description:'Помощь с текстами, анкетами и переводами',subs:['Заполнение анкет','Перевод документов','Редактирование текста','Резюме и портфолио','Деловая переписка','Оцифровка документов']},
  {id:'career',title:'Работа и карьера',mark:'РК',description:'Подготовка к поиску работы и развитию',subs:['Резюме','Подготовка к собеседованию','Карьерная консультация','Поиск вакансий','Портфолио','Наставничество']}
];
const categoryById=id=>categories.find(category=>category.id===id);
const categoryByTitle=title=>categories.find(category=>category.title===title);
const categoryId=value=>categoryById(value)?.id||categoryByTitle(value)?.id||'home';
const categoryLabel=(value,fallback='Разное')=>categoryById(value)?.title||categoryByTitle(value)?.title||fallback;

const seedServices=[
  {id:'demo-lawyer',title:'Консультация семейного юриста',category:'legal',subcategory:'Семейное право',name:'Анна Воронцова',rating:4.9,reviews:86,price_from:1800,city:'Москва',verified:true,distance:2.4,response_minutes:12,description:'Помогу разобраться в семейных, алиментных и наследственных вопросах. Сначала уточним ситуацию, затем составим понятный план действий.',portrait:0,latitude:55.758,longitude:37.617},
  {id:'demo-it',title:'Настройка компьютера и телефона',category:'digital',subcategory:'Компьютерная помощь',name:'Максим Орлов',rating:4.8,reviews:64,price_from:1200,city:'Москва',verified:true,distance:5.1,response_minutes:18,description:'Настрою устройства, резервное копирование, домашнюю сеть и безопасный доступ к сервисам.',portrait:1,latitude:55.742,longitude:37.602},
  {id:'demo-tutor',title:'Английский для учёбы и работы',category:'education',subcategory:'Иностранные языки',name:'Елена Белова',rating:5,reviews:41,price_from:1500,city:'Москва',verified:true,distance:3.7,response_minutes:24,description:'Индивидуальные занятия с практикой речи и планом под вашу цель. Онлайн или очно.',portrait:2,latitude:55.771,longitude:37.635},
  {id:'demo-pets',title:'Выгул и забота о питомцах',category:'pets',subcategory:'Выгул собак',name:'Алексей Миронов',rating:4.9,reviews:109,price_from:700,city:'Москва',verified:true,distance:1.8,response_minutes:9,description:'Прогулки, кормление и спокойный отчёт владельцу после каждого визита.',portrait:3,latitude:55.752,longitude:37.648}
];

const saved=JSON.parse(localStorage.getItem('pomogay_preferences')||'{}');
const state={page:'home',session:null,cloudReady:false,services:[...seedServices],tasks:[],conversations:[],messages:[],people:[],activeConversation:null,chatSearch:'',query:'',catalogMode:'helpers',category:'all',subcategory:'all',verifiedOnly:false,view:'list',radius:Number(saved.radius||25),locationName:saved.locationName||'Москва',coords:saved.coords||{lat:55.7558,lng:37.6176},homeIntent:null,createMode:'task',selectedAddress:null,favorites:[],user:{name:'',city:'Москва',verified:false},maps:new Map(),realtimeChannel:null};
const todayIso=new Date().toISOString().slice(0,10);

function savePreferences(){localStorage.setItem('pomogay_preferences',JSON.stringify({radius:state.radius,locationName:state.locationName,coords:state.coords}))}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function arg(value){return JSON.stringify(value).replace(/</g,'\\u003c')}
function initials(name='Пользователь'){const parts=String(name).trim().split(/\s+/).filter(Boolean);return(parts[0]?.[0]||'П')+(parts.length>1?(parts.at(-1)?.[0]||''):'')}
function formatMoney(value){return value==null?'По договорённости':`от ${Number(value).toLocaleString('ru-RU')} ₽`}
function numberFromText(value){const n=String(value||'').replace(/[^0-9.,]/g,'').replace(',','.');return n?Number(n):null}
function formatDate(value){return value?new Intl.DateTimeFormat('ru-RU',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Время по договорённости'}
function toast(message){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>toastEl.classList.remove('show'),3200)}
function userName(){return state.user.name||state.session?.user?.user_metadata?.name||state.session?.user?.email?.split('@')[0]||'Пользователь'}
function portrait(avatarUrl,name,index=null,size='medium'){
  if(avatarUrl)return `<span class="avatar avatar-${size}" style="background-image:url('${escapeHtml(avatarUrl)}')" aria-hidden="true"></span>`;
  if(Number.isInteger(index))return `<span class="avatar avatar-${size} portrait portrait-${index}" aria-hidden="true"></span>`;
  return `<span class="avatar avatar-${size} avatar-initials" aria-hidden="true">${escapeHtml(initials(name))}</span>`;
}

const navItems=[['home','⌂','Главная'],['catalog','⌕','Поиск'],['create','+','Создать'],['chats','<svg class="nav-chat-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 4h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H10l-5 4v-4a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/></svg>','Чаты'],['profile','<svg class="nav-profile-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm7 8a7 7 0 0 0-14 0"/></svg>','Профиль']];
function shell(content,options={}){
  app.innerHTML=`<div class="app-shell"><header class="topbar"><button class="brand" onclick="go('home')" aria-label="На главную"><span class="brand-mark">П</span><span>Помогай</span></button></header><main class="main ${options.wide?'main-wide':''}">${content}</main><nav class="bottom-nav" aria-label="Основная навигация">${navItems.map(([id,icon,label])=>`<button class="${state.page===id?'active':''} ${id==='create'?'create-nav':''}" onclick="go('${id}')"><span>${icon}</span><small>${label}</small></button>`).join('')}</nav></div>`;
  requestAnimationFrame(afterRender);
}
function go(page){state.page=page;state.activeConversation=null;window.scrollTo({top:0,behavior:'smooth'});render()}

function home(){
  shell(`<section class="home-hero"><div class="intro-copy"><h1>Люди помогают людям</h1><p>Найдите подходящего специалиста или расскажите, чем помочь. Вы выбираете человека, место и удобное время.</p></div></section><section class="intent-grid home-intents"><button class="intent-card find ${state.homeIntent==='find'?'selected':''}" onclick="selectIntent('find')"><span class="intent-icon"><svg class="helping-hand-icon" viewBox="0 0 48 48" aria-hidden="true"><path d="M18 24V9a3.5 3.5 0 0 1 7 0v11-7a3.5 3.5 0 0 1 7 0v9-5a3.5 3.5 0 0 1 7 0v10c0 9-5.5 15-14 15h-2c-5.5 0-9-2.5-12-7l-4-6a3.7 3.7 0 0 1 6-4.3l5 5.3Z"/></svg></span><span><b>Найти помощь</b><small>Выбрать подходящего специалиста</small></span><i>›</i></button><button class="intent-card offer ${state.homeIntent==='need'?'selected':''}" onclick="selectIntent('need')"><span class="intent-icon">+</span><span><b>Нужна помощь</b><small>Выбрать задачу и место</small></span><i>›</i></button></section>${state.homeIntent?homeMapPanel():''}<section class="section-block"><div class="section-heading"><div><h2>Популярные категории</h2><p>Направления с конкретными специализациями</p></div><button class="text-button" onclick="showAllCategories()">Все категории</button></div><div class="category-grid">${categories.slice(0,12).map(categoryCard).join('')}</div></section><section class="section-block specialists-section"><div class="section-heading"><div><h2>Специалисты рядом</h2><p>Выбирайте по опыту, рейтингу и реальным отзывам</p></div><button class="text-button" onclick="go('catalog')">Смотреть всех</button></div><div class="specialist-grid">${filteredServices().slice(0,4).map(serviceCard).join('')}</div></section>`,{wide:true});
}
function homeMapPanel(){
  return `<section class="home-map-panel" id="homeIntentPanel"><div class="map-panel-head"><div><span class="status-pill">${state.homeIntent==='find'?'Ищу помощника':'Хочу разместить задачу'}</span><h2>Где нужна помощь?</h2></div><button class="secondary-button" onclick="useMyLocation('homeMap')">⌖ Использовать моё местоположение</button></div><div class="map-layout"><div id="homeMap" class="map-canvas" aria-label="Карта поиска"></div><div class="map-controls"><label class="range-field"><span>Расстояние <b id="homeRadiusValue">${state.radius} км</b></span><input type="range" min="1" max="500" value="${state.radius}" oninput="previewRadius(this,'homeRadiusValue')" onchange="commitRadius(this.value)"></label><div class="quick-options"><b>${state.homeIntent==='find'?'Что ищем':'Чем помочь?'}</b>${categories.slice(0,6).map(c=>`<button onclick="applyCategory('${c.id}')">${escapeHtml(c.title)}</button>`).join('')}<button onclick="showAllCategories()">Другие категории</button></div><button class="primary-button full" onclick="continueIntent()">${state.homeIntent==='find'?'Показать варианты':'Продолжить к задаче'}</button></div></div></section>`;
}
function categoryCard(category){return `<button class="category-card category-${category.id}" onclick="openCategory('${category.id}')"><span class="category-mark">${category.mark}</span><span><b>${escapeHtml(category.title)}</b><small>${escapeHtml(category.description)}</small></span><i>›</i></button>`}
function selectIntent(intent){state.homeIntent=intent;render();setTimeout(()=>document.querySelector('#homeIntentPanel')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
function continueIntent(){if(state.homeIntent==='find'){state.catalogMode='helpers';state.view='map';go('catalog')}else{state.createMode='task';go('create')}}
function applyCategory(id){state.category=id;state.subcategory='all';continueIntent()}
function openCategory(id){const category=categoryById(id);if(!category)return;modal(`<div class="modal-heading"><span class="category-mark">${category.mark}</span><div><h2>${escapeHtml(category.title)}</h2><p>${escapeHtml(category.description)}</p></div></div><div class="subcategory-list">${category.subs.map(sub=>`<button onclick="chooseSubcategory('${id}',${arg(sub)})"><span>${escapeHtml(sub)}</span><i>›</i></button>`).join('')}</div>`)}
function showAllCategories(){modal(`<h2>Все категории</h2><p class="muted">Выберите основное направление.</p><div class="modal-category-grid">${categories.map(categoryCard).join('')}</div>`)}
function chooseSubcategory(id,sub){state.category=id;state.subcategory=sub;closeModal();if(state.homeIntent==='need'){state.createMode='task';go('create')}else{state.catalogMode='helpers';go('catalog')}}

function distanceFor(row){
  if(Number.isFinite(row.distance))return row.distance;
  if(!Number.isFinite(row.latitude)||!Number.isFinite(row.longitude))return null;
  const a=state.coords,r=6371,dLat=(row.latitude-a.lat)*Math.PI/180,dLon=(row.longitude-a.lng)*Math.PI/180,q=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(row.latitude*Math.PI/180)*Math.sin(dLon/2)**2;
  return Math.round(2*r*Math.asin(Math.sqrt(q))*10)/10;
}
function normalizedService(row,index=0){
  const category=categoryId(row.category);
  return {id:row.id,owner_id:row.owner_id||null,title:row.title,category,subcategory:row.subcategory||categoryById(category)?.subs?.[0]||'',name:row.profiles?.name||row.name||'Помощник',rating:Number(row.profiles?.rating||row.rating||5),reviews:Number(row.reviews||0),price_from:row.price_from,city:row.city||'Москва',verified:!!(row.profiles?.verified??row.verified),demo:String(row.id||'').startsWith('demo-'),distance:distanceFor(row),response_minutes:row.response_minutes||60,description:row.description||'',avatar_url:row.profiles?.avatar_url||row.avatar_url||null,portrait:Number.isInteger(row.portrait)?row.portrait:index%4,latitude:row.latitude,longitude:row.longitude};
}
function filteredServices(){const q=state.query.trim().toLowerCase();return state.services.map(normalizedService).filter(item=>(state.category==='all'||item.category===state.category)&&(state.subcategory==='all'||item.subcategory===state.subcategory)&&(!state.verifiedOnly||item.verified)&&(item.distance==null||item.distance<=state.radius)&&(!q||`${item.title} ${item.name} ${item.subcategory}`.toLowerCase().includes(q)))}
function filteredTasks(){const q=state.query.trim().toLowerCase();return state.tasks.filter(item=>(state.category==='all'||item.category===state.category)&&(state.subcategory==='all'||item.subcategory===state.subcategory)&&(!q||`${item.title} ${item.description||''} ${item.subcategory||''}`.toLowerCase().includes(q)))}
function serviceCard(service,index=0){
  const s=normalizedService(service,index);
  return `<article class="specialist-card"><button class="card-main" onclick="openService(${arg(s.id)})"><div class="specialist-photo">${portrait(s.avatar_url,s.name,s.portrait,'card')}<span class="online-dot" aria-label="Доступен"></span></div><div class="specialist-body"><div class="card-kicker">${escapeHtml(categoryLabel(s.category))} · ${escapeHtml(s.subcategory)}</div><h3>${escapeHtml(s.title)}</h3><div class="person-row"><b>${escapeHtml(s.name)}</b>${s.demo?'<span class="status-pill">Пример</span>':s.verified?'<span class="verified-chip">Проверен</span>':''}</div><div class="card-meta"><span>★ ${s.rating.toFixed(1)}${s.reviews?` (${s.reviews})`:''}</span><span>${s.distance==null?escapeHtml(s.city):`${s.distance} км`}</span></div><div class="card-price">${formatMoney(s.price_from)}</div></div></button><button class="favorite-button ${state.favorites.includes(s.id)?'active':''}" onclick="toggleFavorite(${arg(s.id)})" aria-label="Добавить в избранное">♡</button></article>`;
}
function taskCard(task){return `<article class="task-card"><div class="task-card-head"><span class="status-pill">Задача пользователя</span><span>${formatDate(task.scheduled_at)}</span></div><h3>${escapeHtml(task.title)}</h3><p>${escapeHtml(task.description||'')}</p><div class="task-tags"><span>${escapeHtml(categoryLabel(task.category))}</span>${task.subcategory?`<span>${escapeHtml(task.subcategory)}</span>`:''}<span>${escapeHtml(task.address||'Адрес после отклика')}</span></div><div class="task-bottom"><b>${task.budget==null?'Бюджет по договорённости':`${Number(task.budget).toLocaleString('ru-RU')} ₽`}</b><button class="secondary-button" onclick="respondToTask(${arg(task.id)})">Откликнуться</button></div></article>`}

function catalog(){
  const items=state.catalogMode==='helpers'?filteredServices():filteredTasks();
  shell(`<section class="catalog-head"><div><span class="eyebrow">Поиск рядом</span><h1>${state.catalogMode==='helpers'?'Специалисты':'Задачи пользователей'}</h1></div><div class="segmented"><button class="${state.catalogMode==='helpers'?'active':''}" onclick="setCatalogMode('helpers')">Специалисты</button><button class="${state.catalogMode==='tasks'?'active':''}" onclick="setCatalogMode('tasks')">Задачи</button></div></section><form class="search-row" onsubmit="searchCatalog(event)"><input name="query" value="${escapeHtml(state.query)}" placeholder="Специалист, услуга или ФИО"><button class="primary-button">Найти</button><button type="button" class="icon-button" onclick="showFilters()" aria-label="Открыть фильтры">≡</button></form><section class="catalog-tools"><div class="category-scroll"><button class="filter-chip ${state.category==='all'?'active':''}" onclick="setCategory('all')">Все</button>${categories.map(c=>`<button class="filter-chip ${state.category===c.id?'active':''}" onclick="setCategory('${c.id}')">${escapeHtml(c.title)}</button>`).join('')}</div><div class="view-switch"><button class="${state.view==='list'?'active':''}" onclick="setView('list')">Список</button><button class="${state.view==='map'?'active':''}" onclick="setView('map')">Карта</button></div></section>${activeSubcategoryBar()}${state.view==='map'?catalogMap(items):catalogList(items)}`,{wide:true});
}
function activeSubcategoryBar(){const category=categoryById(state.category);if(!category)return'';return `<div class="subcategory-scroll"><button class="${state.subcategory==='all'?'active':''}" onclick="setSubcategory('all')">Все направления</button>${category.subs.map(sub=>`<button class="${state.subcategory===sub?'active':''}" onclick="setSubcategory(${arg(sub)})">${escapeHtml(sub)}</button>`).join('')}</div>`}
function catalogList(items){if(!items.length)return emptyState(state.catalogMode==='tasks'?'Пока нет открытых задач по этим условиям':'Ничего не найдено','Измените категорию, расстояние или поисковый запрос.');return state.catalogMode==='helpers'?`<div class="specialist-grid catalog-grid">${items.map(serviceCard).join('')}</div>`:`<div class="task-list">${items.map(taskCard).join('')}</div>`}
function catalogMap(items){
  let results=emptyState('На карте пока пусто','Измените фильтры или расстояние.');
  if(items.length)results=state.catalogMode==='helpers'?items.slice(0,6).map(serviceCard).join(''):items.slice(0,6).map(taskCard).join('');
  return `<section class="catalog-map-layout"><div class="map-column"><div class="map-toolbar"><button class="secondary-button" onclick="useMyLocation('catalogMap')">⌖ Использовать моё местоположение</button><span>${items.length} вариантов</span></div><div id="catalogMap" class="map-canvas map-large"></div><label class="range-field map-radius"><span>Расстояние <b id="catalogRadiusValue">${state.radius} км</b></span><input type="range" min="1" max="500" value="${state.radius}" oninput="previewRadius(this,'catalogRadiusValue')" onchange="commitRadius(this.value)"></label></div><aside class="map-results">${results}</aside></section>`;
}
function emptyState(title,text){return `<div class="empty-state"><span>○</span><h3>${escapeHtml(title)}</h3><p>${escapeHtml(text)}</p></div>`}
function searchCatalog(event){event.preventDefault();state.query=String(new FormData(event.currentTarget).get('query')||'').trim();render()}
function setCatalogMode(mode){state.catalogMode=mode;render()}
function setCategory(id){state.category=id;state.subcategory='all';render()}
function setSubcategory(value){state.subcategory=value;render()}
function setView(view){state.view=view;render()}
function previewRadius(input,labelId){state.radius=Number(input.value);document.querySelector(`#${labelId}`).textContent=`${input.value} км`;updateMapRadius()}
function commitRadius(value){state.radius=Number(value);savePreferences();render()}
function subcategoryOptions(category,selected,includeAll=false){const item=categoryById(category);return `${includeAll?'<option value="all">Все направления</option>':''}${(item?.subs||[]).map(sub=>`<option value="${escapeHtml(sub)}" ${selected===sub?'selected':''}>${escapeHtml(sub)}</option>`).join('')}`}
function showFilters(){modal(`<h2>Фильтры поиска</h2><div class="form-grid"><label class="field"><span>Основная категория</span><select id="filterCategory" onchange="refreshFilterSubcategories(this.value)"><option value="all">Все категории</option>${categories.map(c=>`<option value="${c.id}" ${state.category===c.id?'selected':''}>${escapeHtml(c.title)}</option>`).join('')}</select></label><label class="field"><span>Направление</span><select id="filterSubcategory">${subcategoryOptions(state.category,state.subcategory,true)}</select></label><label class="range-field full-field"><span>Расстояние <b id="modalRadiusValue">${state.radius} км</b></span><input id="filterRadius" type="range" min="1" max="500" value="${state.radius}" oninput="document.querySelector('#modalRadiusValue').textContent=this.value+' км'"></label><label class="check-row"><input id="filterVerified" type="checkbox" ${state.verifiedOnly?'checked':''}><span><b>Только с подтверждённой личностью</b><small>Показывать пользователей, прошедших проверку</small></span></label><button class="primary-button full-field" onclick="applyFilters()">Применить</button></div>`)}
function refreshFilterSubcategories(category){document.querySelector('#filterSubcategory').innerHTML=subcategoryOptions(category,'all',true)}
function applyFilters(){state.category=document.querySelector('#filterCategory').value;state.subcategory=document.querySelector('#filterSubcategory').value;state.radius=Number(document.querySelector('#filterRadius').value);state.verifiedOnly=document.querySelector('#filterVerified').checked;savePreferences();closeModal();render()}

function create(){
  if(!state.session){shell(`<section class="auth-gate"><h1>Войдите, чтобы публиковать</h1><p>Задачи и предложения помощи связаны с профилем реального пользователя.</p><div class="button-row"><button class="primary-button" onclick="showAuth('signup')">Создать аккаунт</button><button class="secondary-button" onclick="showAuth('login')">Войти</button></div></section>`);return}
  const category=state.category==='all'?'home':state.category;
  shell(`<section class="create-head"><h1>${state.createMode==='task'?'Попросить о помощи':'Хочу помогать'}</h1><div class="segmented create-tabs"><button class="${state.createMode==='task'?'active':''}" onclick="setCreateMode('task')">Нужна помощь</button><button class="${state.createMode==='service'?'active':''}" onclick="setCreateMode('service')">Хочу помогать</button></div></section><form class="publish-form" onsubmit="${state.createMode==='task'?'publishTask(event)':'publishService(event)'}"><section class="form-section"><div class="form-section-title"><span>1</span><div><h2>${state.createMode==='task'?'Чем помочь?':'Как помогаю'}</h2><p>Коротко и конкретно опишите результат.</p></div></div><label class="field"><span>${state.createMode==='task'?'Название задачи':'Как помогаю'}</span><input name="title" required minlength="3" maxlength="120" placeholder="${state.createMode==='task'?'Например, выгулять собаку вечером':'Например, консультирую по семейному праву'}"></label><label class="field"><span>Подробности</span><textarea name="description" required minlength="10" maxlength="4000" rows="5" placeholder="Добавьте важные детали, объём работы и ожидания"></textarea></label></section><section class="form-section"><div class="form-section-title"><span>2</span><div><h2>Категория</h2><p>Выберите направление и специализацию.</p></div></div><div class="two-fields"><label class="field"><span>Основная категория</span><select name="category" onchange="updateCreateSubcategories(this.value)" required>${categories.map(c=>`<option value="${c.id}" ${category===c.id?'selected':''}>${escapeHtml(c.title)}</option>`).join('')}</select></label><label class="field"><span>Направление</span><select id="createSubcategory" name="subcategory" required>${subcategoryOptions(category,state.subcategory==='all'?'':state.subcategory)}</select></label></div></section>${state.createMode==='task'?taskFields():serviceFields()}<div id="publishError" class="form-error" hidden></div><button class="primary-button publish-button">${state.createMode==='task'?'Опубликовать задачу':'Опубликовать помощь'}</button></form>`);
}
function taskFields(){
  const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());
  return `<section class="form-section"><div class="form-section-title"><span>3</span><div><h2>Место и время</h2><p>Точка на карте видна только в пределах, необходимых для поиска.</p></div></div><label class="field"><span>Адрес или район</span><div class="input-action"><input id="addressInput" name="address" required maxlength="200" value="${escapeHtml(state.selectedAddress?.address||'')}" placeholder="Улица, район или ориентир"><button type="button" onclick="openAddressPicker()">Выбрать на карте</button></div></label><input type="hidden" name="latitude" value="${state.selectedAddress?.lat||''}"><input type="hidden" name="longitude" value="${state.selectedAddress?.lng||''}"><div class="two-fields"><label class="field"><span>Дата</span><input name="date" type="date" min="${today.toISOString().slice(0,10)}" required></label><label class="field"><span>Время</span><input name="time" type="time" required></label></div><label class="field"><span>Бюджет, ₽</span><input name="budget" inputmode="decimal" placeholder="Можно оставить пустым"></label></section>`;
}
function serviceFields(){return `<section class="form-section"><div class="form-section-title"><span>3</span><div><h2>Условия</h2><p>Укажите стартовую цену и формат помощи.</p></div></div><div class="two-fields"><label class="field"><span>Цена от, ₽</span><input name="price" inputmode="decimal" required placeholder="1500"></label><label class="field"><span>Формат</span><select name="format"><option>С выездом</option><option>Онлайн</option><option>У меня</option><option>По договорённости</option></select></label></div></section>`}
function setCreateMode(mode){state.createMode=mode;render()}
function updateCreateSubcategories(category){document.querySelector('#createSubcategory').innerHTML=subcategoryOptions(category,'')}
function openAddressPicker(){modal(`<h2>Выберите место на карте</h2><p class="muted">Нажмите на карту или определите текущее местоположение.</p><div id="addressMap" class="map-canvas modal-map"></div><div class="button-row modal-actions"><button class="secondary-button" onclick="useMyLocation('addressMap',true)">⌖ Моё местоположение</button><button class="primary-button" onclick="confirmAddress()">Выбрать точку</button></div>`);requestAnimationFrame(()=>initMap('addressMap',[],true))}
function confirmAddress(){const map=state.maps.get('addressMap'),center=map?.__selected||map?.getCenter?.()||{lat:state.coords.lat,lng:state.coords.lng};state.selectedAddress={address:`${state.locationName}, выбранная точка`,lat:Number(center.lat.toFixed(6)),lng:Number(center.lng.toFixed(6))};closeModal();render();toast('Место добавлено к публикации')}
function setFormBusy(form,busy){const button=form.querySelector('button[type="submit"],.publish-button');if(button){button.disabled=busy;button.dataset.label||=button.textContent;button.textContent=busy?'Сохраняем…':button.dataset.label}}
function showFormError(form,message){const box=form.querySelector('.form-error');if(box){box.hidden=false;box.textContent=message}else toast(message)}

async function publishTask(event){
  event.preventDefault();if(!requireAuth())return;const form=event.currentTarget,d=Object.fromEntries(new FormData(form));setFormBusy(form,true);
  try{
    const scheduledAt=new Date(`${d.date}T${d.time}`);if(Number.isNaN(scheduledAt.getTime()))throw new Error('Выберите дату и время.');
    const row={customer_id:state.session.user.id,title:String(d.title).trim(),category:d.category,subcategory:d.subcategory,description:String(d.description).trim(),budget:numberFromText(d.budget),address:String(d.address).trim(),latitude:d.latitude?Number(d.latitude):null,longitude:d.longitude?Number(d.longitude):null,scheduled_at:scheduledAt.toISOString(),status:'open'};
    let result=await sb.from('tasks').insert(row).select().single();
    if(result.error&&String(result.error.message).includes('subcategory')){delete row.subcategory;result=await sb.from('tasks').insert(row).select().single()}
    if(result.error)throw result.error;state.selectedAddress=null;await loadCloud();state.catalogMode='tasks';state.page='catalog';render();toast('Задача опубликована');
  }catch(error){showFormError(form,friendlyDatabaseError(error,'Не удалось опубликовать задачу.'))}finally{setFormBusy(form,false)}
}
async function publishService(event){
  event.preventDefault();if(!requireAuth())return;const form=event.currentTarget,d=Object.fromEntries(new FormData(form));setFormBusy(form,true);
  try{
    const row={owner_id:state.session.user.id,title:String(d.title).trim(),category:d.category,subcategory:d.subcategory,description:String(d.description).trim(),price_from:numberFromText(d.price),city:state.user.city||'Москва',response_minutes:60,is_active:true};
    let result=await sb.from('services').insert(row).select().single();
    if(result.error&&String(result.error.message).includes('subcategory')){delete row.subcategory;result=await sb.from('services').insert(row).select().single()}
    if(result.error)throw result.error;await loadCloud();state.catalogMode='helpers';state.page='catalog';render();toast('Предложение помощи опубликовано');
  }catch(error){showFormError(form,friendlyDatabaseError(error,'Не удалось опубликовать помощь.'))}finally{setFormBusy(form,false)}
}

function chats(){
  if(!state.session){shell(`<section class="auth-gate"><h1>Чаты только между пользователями</h1><p>Войдите, чтобы увидеть свои диалоги и найти человека по ФИО.</p><button class="primary-button" onclick="showAuth('login')">Войти</button></section>`);return}
  const active=state.conversations.find(item=>item.id===state.activeConversation);
  shell(`<section class="chat-page"><aside class="chat-sidebar"><div class="chat-sidebar-head"><div><h1>Чаты</h1></div></div><form class="people-search" onsubmit="searchPeople(event)"><input name="person" value="${escapeHtml(state.chatSearch)}" placeholder="Найти человека по ФИО"><button aria-label="Найти">⌕</button></form>${state.people.length?peopleResults():conversationList()}</aside><section class="chat-dialog">${active?dialogView(active):emptyState('Выберите диалог','Здесь появится переписка с пользователем приложения.')}</section></section>`,{wide:true});
  if(active)scrollMessages();
}
function conversationList(){
  if(!state.conversations.length)return emptyState('Диалогов пока нет','Найдите пользователя по ФИО или откликнитесь на задачу.');
  return `<div class="conversation-list">${state.conversations.map(c=>{const other=conversationPartner(c),last=c.lastMessage;return `<button class="conversation-item ${state.activeConversation===c.id?'active':''}" onclick="openConversation(${arg(c.id)})">${portrait(other.avatar_url,other.name,null,'small')}<span><b>${escapeHtml(other.name||'Пользователь')}</b><small>${escapeHtml(last?.body||'Диалог создан')}</small></span><time>${last?new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(last.created_at)):''}</time></button>`}).join('')}</div>`;
}
function peopleResults(){return `<div class="people-results"><div class="results-caption"><span>Пользователи</span><button onclick="clearPeopleSearch()">Закрыть</button></div>${state.people.map(person=>`<div class="person-result">${portrait(person.avatar_url,person.name,null,'small')}<span><b>${escapeHtml(person.name)}</b><small>${escapeHtml(person.city||'Город не указан')}</small></span><button onclick="startDirectChat(${arg(person.id)})">Написать</button></div>`).join('')}</div>`}
function conversationPartner(conversation){const uid=state.session?.user?.id;return conversation.customer_id===uid?(conversation.helper||{}):(conversation.customer||{})}
function dialogView(conversation){const other=conversationPartner(conversation);return `<header class="dialog-head">${portrait(other.avatar_url,other.name,null,'small')}<span><b>${escapeHtml(other.name||'Пользователь')}</b><small>Пользователь «Помогай»</small></span></header><div class="message-list" id="messageList">${state.messages.length?state.messages.map(message=>`<div class="message ${message.sender_id===state.session.user.id?'mine':''}"><p>${escapeHtml(message.body)}</p><time>${new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(message.created_at))}</time></div>`).join(''):emptyState('Сообщений пока нет','Начните диалог. Сообщение увидит только второй участник.')}</div><form class="message-form" onsubmit="sendMessage(event)"><input name="body" required maxlength="4000" autocomplete="off" placeholder="Напишите сообщение"><button class="primary-button">Отправить</button></form>`}
async function searchPeople(event){event.preventDefault();const q=String(new FormData(event.currentTarget).get('person')||'').trim();state.chatSearch=q;if(q.length<2){state.people=[];render();return toast('Введите минимум 2 буквы')}const result=await sb.from('profiles').select('id,name,city,avatar_url,verified').ilike('name',`%${q.replace(/[%_,]/g,'')}%`).neq('id',state.session.user.id).limit(20);if(result.error)return toast('Не удалось выполнить поиск');state.people=result.data||[];render()}
function clearPeopleSearch(){state.chatSearch='';state.people=[];render()}
async function startDirectChat(otherUser){if(!requireAuth())return;const result=await sb.rpc('start_direct_conversation',{other_user:otherUser});if(result.error)return toast(result.error.message.includes('function')?'Прямые чаты станут доступны после обновления базы':'Не удалось создать диалог');state.people=[];state.chatSearch='';await loadConversations();await openConversation(result.data);toast('Диалог открыт')}
async function openConversation(id){state.activeConversation=id;const result=await sb.from('messages').select('id,conversation_id,sender_id,body,read_at,created_at').eq('conversation_id',id).order('created_at',{ascending:true});if(result.error)return toast('Не удалось загрузить сообщения');state.messages=result.data||[];render();subscribeToConversation(id)}
async function sendMessage(event){event.preventDefault();const form=event.currentTarget,body=String(new FormData(form).get('body')||'').trim();if(!body)return;const result=await sb.from('messages').insert({conversation_id:state.activeConversation,sender_id:state.session.user.id,body}).select().single();if(result.error)return toast('Не удалось отправить сообщение');form.reset();if(!state.messages.some(m=>m.id===result.data.id))state.messages.push(result.data);render();await loadConversations(false)}
function subscribeToConversation(id){if(!sb)return;if(state.realtimeChannel)sb.removeChannel(state.realtimeChannel);state.realtimeChannel=sb.channel(`conversation:${id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},payload=>{if(!state.messages.some(m=>m.id===payload.new.id)){state.messages.push(payload.new);render()}}).subscribe()}
function scrollMessages(){requestAnimationFrame(()=>{const element=document.querySelector('#messageList');if(element)element.scrollTop=element.scrollHeight})}

function profile(){
  if(!state.session){shell(`<section class="guest-profile"><div class="guest-avatar">П</div><span class="eyebrow">Личный профиль</span><h1>Ваше место в «Помогай»</h1><p>Управляйте публикациями, безопасностью, удостоверением личности и продвижением.</p><div class="button-row"><button class="primary-button" onclick="showAuth('login')">Войти</button><button class="secondary-button" onclick="showAuth('signup')">Создать аккаунт</button></div></section>`);return}
  const name=userName();
  shell(`<section class="profile-hero"><div class="profile-person">${portrait(state.user.avatar_url,name,null,'large')}<div><h1>${escapeHtml(name)}</h1><p>${escapeHtml(state.user.city||'Москва')}</p><div class="profile-badges">${state.user.verified?'<span class="verified-chip">Личность подтверждена</span>':'<span class="status-pill">Проверка не пройдена</span>'}</div></div></div><button class="secondary-button" onclick="editProfile()">Редактировать профиль</button></section>${profileSection('Профиль и публикации',[["ПР","Данные профиля","Фото, контакты, город, опыт и описание","editProfile()"],["МО","Мои объявления","Задачи и предложения помощи","go('create')"]])}${profileSection('Удостоверение личности',[["ID","Проверка личности",state.user.verified?'ФИО и дата рождения защищены':'Подтвердите личность перед работой с заказами',"verifyIdentity()"],["БЗ","Безопасность","Вход, пароль, приватность и жалобы","showSafety()"]])}${profileSection('Возможности профиля',[["БН","Помогай Бонусы","Получение бонусов и пакеты пополнения","showBonusShop()"],["ПР","Продвижение","Сравнить оплату рублями и бонусами","showPromotion()"]])}${profileSection('Настройки',[["НС","Настройки и вход","Уведомления, восстановление пароля, выход","showAccountSettings()"],["ПО","Поддержка","Помощь по работе сервиса","showSupport()"]])}`,{wide:true});
}
function profileSection(title,items){return `<section class="profile-section"><h2>${title}</h2><div class="profile-menu">${items.map(([mark,name,description,action])=>`<button onclick="${action}"><span class="menu-mark">${mark}</span><span><b>${name}</b><small>${description}</small></span><i>›</i></button>`).join('')}</div></section>`}
function editProfile(){
  const locked=!!state.user.verified;
  modal(`<h2>Редактирование профиля</h2><form class="form-grid" onsubmit="saveProfile(event)"><div class="avatar-editor">${portrait(state.user.avatar_url,userName(),null,'large')}<label class="secondary-button">Выбрать фото<input name="avatar" type="file" accept="image/png,image/jpeg,image/webp" hidden></label></div><label class="field full-field"><span>Полное ФИО ${locked?'· подтверждено':''}</span><input name="name" required minlength="5" maxlength="120" autocomplete="name" value="${escapeHtml(userName())}" ${locked?'readonly':''}></label><label class="field"><span>Дата рождения</span><input name="birth_date" type="date" min="1900-01-01" max="${todayIso}" value="${escapeHtml(state.user.birth_date||'')}" required ${locked?'readonly':''}></label><label class="field"><span>Город</span><input name="city" required minlength="2" maxlength="120" value="${escapeHtml(state.user.city||'Москва')}"></label><label class="field"><span>Телефон</span><input name="phone" type="tel" maxlength="30" autocomplete="tel" value="${escapeHtml(state.user.phone||'')}"></label><label class="field"><span>Опыт, лет</span><input name="experience_years" type="number" min="0" max="80" value="${escapeHtml(state.user.experience_years??'')}"></label><label class="field full-field"><span>О себе и чем можете помочь</span><textarea name="bio" maxlength="1000" rows="4">${escapeHtml(state.user.bio||'')}</textarea></label><label class="field full-field"><span>Языки</span><input name="languages" maxlength="200" value="${escapeHtml(state.user.languages||'')}" placeholder="Русский, английский"></label><div id="profileError" class="form-error full-field" hidden></div><button class="primary-button full-field">Сохранить</button></form>`);
}
function validFullName(name){return String(name||'').trim().split(/\s+/).filter(part=>part.length>=2).length>=3}
async function saveProfile(event){
  event.preventDefault();if(!state.session){showAuth('login');return}const form=event.currentTarget,d=Object.fromEntries(new FormData(form));d.name=String(d.name||'').trim().replace(/\s+/g,' ');d.city=String(d.city||'').trim();if(!validFullName(d.name))return showFormError(form,'Укажите полное ФИО: фамилию, имя и отчество.');setFormBusy(form,true);
  try{
    let avatarUrl=state.user.avatar_url||null;const file=form.querySelector('[name="avatar"]').files?.[0];if(file)avatarUrl=await uploadAvatar(file);
    const row={name:d.name,city:d.city,avatar_url:avatarUrl,bio:String(d.bio||'').trim()||null,languages:String(d.languages||'').trim()||null,experience_years:d.experience_years===''?null:Number(d.experience_years)};
    let result=await sb.from('profiles').update(row).eq('id',state.session.user.id).select().single();
    if(result.error&&String(result.error.message).match(/bio|languages|experience_years/)){const fallback={name:row.name,city:row.city,avatar_url:row.avatar_url};result=await sb.from('profiles').update(fallback).eq('id',state.session.user.id).select().single()}
    if(result.error)throw result.error;
    const privateResult=await sb.from('profile_private').upsert({id:state.session.user.id,birth_date:d.birth_date||null,phone:String(d.phone||'').trim()||null},{onConflict:'id'});
    if(privateResult.error&&!String(privateResult.error.message).includes('profile_private'))throw privateResult.error;
    await sb.auth.updateUser({data:{name:d.name,city:d.city}});await ensureProfile();closeModal();render();toast('Профиль обновлён');
  }catch(error){showFormError(form,friendlyDatabaseError(error,'Не удалось сохранить профиль.'))}finally{setFormBusy(form,false)}
}
async function uploadAvatar(file){if(file.size>5*1024*1024)throw new Error('Файл фото должен быть не больше 5 МБ.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Поддерживаются JPG, PNG и WebP.');const extension=file.type.split('/')[1].replace('jpeg','jpg'),path=`${state.session.user.id}/avatar.${extension}`,upload=await sb.storage.from('avatars').upload(path,file,{upsert:true,contentType:file.type});if(upload.error)throw upload.error;return sb.storage.from('avatars').getPublicUrl(path).data.publicUrl}
function verifyIdentity(){modal(`<h2>Удостоверение личности</h2><div class="notice">Проверка документов пока не подключена. Не загружайте паспорт или другие документы в эту версию приложения.</div><p class="muted">Перед запуском нужен отдельный KYC-провайдер, закрытое хранилище и ручная проверка спорных случаев. После подтверждения ФИО и дата рождения станут недоступны для самостоятельного изменения.</p><button class="primary-button full" onclick="closeModal()">Понятно</button>`)}
function showSafety(){modal(`<h2>Безопасность</h2><div class="settings-list"><button onclick="showPasswordReset()"><span><b>Сбросить пароль</b><small>Получить безопасную ссылку на email</small></span><i>›</i></button><button onclick="showLegal('privacy')"><span><b>Конфиденциальность</b><small>Как используются данные профиля</small></span><i>›</i></button><button onclick="showLegal('rules')"><span><b>Правила общения</b><small>Безопасные задачи и сообщения</small></span><i>›</i></button></div>`)}
function showAccountSettings(){modal(`<h2>Настройки и вход</h2><div class="settings-list"><label><span><b>Уведомления о сообщениях</b><small>Новые чаты и отклики</small></span><input type="checkbox" checked></label><label><span><b>Показывать статус онлайн</b><small>Доступность видят другие пользователи</small></span><input type="checkbox"></label><button onclick="showPasswordReset()"><span><b>Изменить пароль</b><small>Отправить ссылку на ${escapeHtml(state.session?.user?.email||'email')}</small></span><i>›</i></button></div><button class="danger-button full" onclick="signOut()">Выйти из аккаунта</button>`)}
function showSupport(){modal(`<h2>Поддержка</h2><div class="notice">Канал поддержки пока не подключён. Не отправляйте через этот экран персональные документы или платёжные данные.</div><button class="primary-button full" onclick="closeModal()">Понятно</button>`)}

const bonusPacks=[{rub:99,bonus:100},{rub:499,bonus:550},{rub:999,bonus:1200},{rub:2499,bonus:3200}];
const promotions=[{name:'Поднять на 3 часа',rub:79,bonus:65},{name:'Выделить на 7 дней',rub:149,bonus:120},{name:'Срочное на 24 часа',rub:199,bonus:160},{name:'VIP на 24 часа',rub:299,bonus:240}];
function showBonusShop(){modal(`<h2>Помогай Бонусы</h2><div class="notice">Демонстрационный расчёт: реальные деньги не списываются, покупка и начисление бонусов пока не подключены.</div><div class="earn-grid"><div><b>2 рекламных видео</b><strong>+1 бонус</strong><small>После подключения рекламного партнёра</small></div><div><b>3 выполненные задачи</b><strong>+50 бонусов</strong><small>После подтверждения обеими сторонами</small></div></div><h3>Пакеты пополнения</h3><div class="price-table">${bonusPacks.map((item,index)=>`<div class="price-row ${index===2?'recommended':''}"><span><b>${item.bonus} бонусов</b><small>${(item.rub/item.bonus).toFixed(2).replace('.',',')} ₽ за бонус</small></span><strong>${item.rub.toLocaleString('ru-RU')} ₽</strong><button onclick="paymentUnavailable()">Выбрать</button></div>`).join('')}</div>`)}
function showPromotion(){modal(`<h2>Продвижение объявления</h2><p class="muted">Бонусами примерно на 20% выгоднее. Стоимость видна до подтверждения.</p><div class="comparison-head"><span>Вариант</span><span>Рубли</span><span>Бонусы</span></div><div class="promotion-table">${promotions.map(item=>`<div><b>${item.name}</b><button onclick="paymentUnavailable()">${item.rub} ₽</button><button class="bonus-pay" onclick="paymentUnavailable()">${item.bonus} Б</button></div>`).join('')}</div><div class="notice subtle">Оплата станет доступна только после подключения платёжного провайдера, чеков и правил возврата.</div>`)}
function paymentUnavailable(){toast('Оплата пока не подключена: списаний не будет')}

function modal(html){closeModal(true);document.body.classList.add('modal-open');document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="modal" onclick="if(event.target===this)closeModal()"><section class="modal" role="dialog" aria-modal="true"><header class="modal-top"><button class="modal-handle" aria-label="Закрыть окно" onclick="closeModal()"></button><button class="modal-close" aria-label="Закрыть" onclick="closeModal()">×</button></header><div class="modal-content">${html}</div></section></div>`);requestAnimationFrame(()=>document.querySelector('#modal')?.classList.add('open'))}
function closeModal(immediate=false){const wrap=document.querySelector('#modal');if(!wrap)return;document.body.classList.remove('modal-open');const addressMap=state.maps.get('addressMap');if(addressMap){try{addressMap.remove()}catch{}state.maps.delete('addressMap')}if(immediate){wrap.remove();return}wrap.classList.remove('open');setTimeout(()=>wrap.remove(),180)}
function openService(id){const service=filteredServices().find(item=>item.id===id)||state.services.map(normalizedService).find(item=>item.id===id);if(!service)return;modal(`<div class="service-modal-head">${portrait(service.avatar_url,service.name,service.portrait,'large')}<div><span class="card-kicker">${escapeHtml(categoryLabel(service.category))} · ${escapeHtml(service.subcategory)}</span><h2>${escapeHtml(service.title)}</h2><p>${escapeHtml(service.name)}</p></div></div><div class="service-facts"><span><b>★ ${service.rating.toFixed(1)}</b><small>${service.reviews} отзывов</small></span><span><b>${formatMoney(service.price_from)}</b><small>Стоимость</small></span><span><b>${service.distance==null?escapeHtml(service.city):`${service.distance} км`}</b><small>Расположение</small></span></div><p class="service-description">${escapeHtml(service.description)}</p><div class="button-row"><button class="primary-button" onclick="contactService(${arg(service.owner_id)})">Написать</button><button class="secondary-button" onclick="toggleFavorite(${arg(service.id)})">${state.favorites.includes(service.id)?'Убрать из избранного':'В избранное'}</button></div><button class="text-button report-link" onclick="reportUser(${arg(service.owner_id)})">Пожаловаться</button>`)}
function contactService(ownerId){if(!ownerId)return toast('Это демонстрационный профиль: чат недоступен');closeModal();startDirectChat(ownerId)}
function reportUser(){modal(`<h2>Жалоба</h2><div class="notice">Отправка жалоб пока не подключена. Если есть непосредственная угроза, прекратите общение и обратитесь в экстренную службу.</div><button class="primary-button full" onclick="closeModal()">Понятно</button>`)}
async function toggleFavorite(id){if(!state.session){showAuth('login');return}if(String(id).startsWith('demo-'))return toast('Демонстрационный профиль нельзя добавить в избранное');const uid=state.session.user.id;if(state.favorites.includes(id)){const result=await sb.from('favorites').delete().eq('user_id',uid).eq('service_id',id);if(result.error)return toast('Не удалось обновить избранное');state.favorites=state.favorites.filter(item=>item!==id)}else{const result=await sb.from('favorites').insert({user_id:uid,service_id:id});if(result.error)return toast('Не удалось обновить избранное');state.favorites.push(id)}render();toast('Избранное обновлено')}
function respondToTask(){if(!requireAuth())return;toast('Отклик можно отправить после заполнения профиля помощника')}

function showLocationMenu(){modal(`<h2>Местоположение</h2><div class="settings-list"><button onclick="useMyLocation(null)"><span><b>Использовать моё местоположение</b><small>Определить координаты устройства</small></span><i>⌖</i></button><button onclick="chooseCity()"><span><b>Выбрать город</b><small>Сейчас: ${escapeHtml(state.locationName)}</small></span><i>›</i></button><button onclick="closeModal();state.view='map';go('catalog')"><span><b>Открыть карту</b><small>Радиус настраивается прямо на карте</small></span><i>›</i></button></div>`)}
function chooseCity(){modal(`<h2>Выберите город</h2><div class="subcategory-list">${[{name:'Москва',lat:55.7558,lng:37.6176},{name:'Санкт-Петербург',lat:59.9343,lng:30.3351},{name:'Казань',lat:55.7961,lng:49.1064},{name:'Екатеринбург',lat:56.8389,lng:60.6057},{name:'Новосибирск',lat:55.0084,lng:82.9357},{name:'Сочи',lat:43.5855,lng:39.7231}].map(city=>`<button onclick="setCity(${arg(city.name)},${city.lat},${city.lng})"><span>${city.name}</span><i>›</i></button>`).join('')}</div>`)}
function setCity(name,lat,lng){state.locationName=name;state.coords={lat,lng};savePreferences();closeModal();render();toast(`Город: ${name}`)}
function useMyLocation(mapId,selectable=false){
  if(!navigator.geolocation)return toast('Геолокация не поддерживается');toast('Определяем местоположение…');navigator.geolocation.getCurrentPosition(position=>{state.coords={lat:position.coords.latitude,lng:position.coords.longitude};state.locationName='Рядом со мной';savePreferences();const map=mapId&&state.maps.get(mapId);if(map){map.setView([state.coords.lat,state.coords.lng],13);if(selectable)map.fire('click',{latlng:{lat:state.coords.lat,lng:state.coords.lng}})}else{closeModal();render()}toast('Местоположение определено')},()=>toast('Разрешите доступ к геолокации в настройках браузера'),{enableHighAccuracy:true,timeout:10000,maximumAge:300000});
}
function mountDesktopNav(){const header=document.querySelector('.topbar');if(!header||header.querySelector('.desktop-nav'))return;const nav=document.createElement('nav');nav.className='desktop-nav';nav.setAttribute('aria-label','Основная навигация');nav.innerHTML=navItems.map(([id,icon,label])=>`<button class="${state.page===id?'active':''} ${id==='create'?'create-nav':''}" onclick="go('${id}')" ${state.page===id?'aria-current="page"':''}><span>${icon}</span><small>${label}</small></button>`).join('');header.querySelector('.brand')?.after(nav)}
function mountProfileFavorites(){if(state.page!=='profile'||!state.session)return;const bonus=[...document.querySelectorAll('.profile-menu>button')].find(button=>button.textContent.includes('Помогай Бонусы'));if(!bonus||bonus.parentElement.querySelector('[data-favorites-menu]'))return;const button=document.createElement('button');button.dataset.favoritesMenu='true';button.setAttribute('onclick','showFavorites()');button.innerHTML=`<span class="menu-mark">ИЗ</span><span><b>Избранные</b><small>Сохранённые специалисты, которых легко найти снова</small></span><i>›</i>`;bonus.after(button)}
function afterRender(){mountDesktopNav();mountProfileFavorites();if(document.querySelector('#homeMap'))initMap('homeMap',filteredServices());if(document.querySelector('#catalogMap'))initMap('catalogMap',state.catalogMode==='helpers'?filteredServices():filteredTasks())}
function showFavorites(){if(!state.session)return showAuth('login');const items=state.services.map(normalizedService).filter(item=>state.favorites.includes(item.id));modal(`<h2>Избранные специалисты</h2><p class="muted">Здесь сохраняются люди, к которым вы хотите вернуться.</p>${items.length?`<div class="favorite-people">${items.map(item=>`<article class="favorite-person"><button onclick="openService(${arg(item.id)})">${portrait(item.avatar_url,item.name,item.portrait,'small')}<span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.title)}</small></span></button><button class="favorite-remove" onclick="removeFavorite(${arg(item.id)})" aria-label="Удалить из избранного">×</button></article>`).join('')}</div>`:emptyState('Избранных пока нет','Нажмите на сердечко в карточке специалиста, чтобы сохранить его здесь.')}`)}
async function removeFavorite(id){await toggleFavorite(id);showFavorites()}
let yandexMapsPromise;
function loadYandexMaps(){
  if(window.ymaps)return Promise.resolve(window.ymaps);
  const key=String((window.POMOGAY_CONFIG||{}).YANDEX_MAPS_API_KEY||'').trim();if(!key)return Promise.resolve(null);
  if(!yandexMapsPromise)yandexMapsPromise=new Promise(resolve=>{const script=document.createElement('script');script.src=`https://api-maps.yandex.ru/2.1/?apikey=${encodeURIComponent(key)}&lang=ru_RU`;script.onload=()=>window.ymaps?.ready(()=>resolve(window.ymaps));script.onerror=()=>resolve(null);document.head.append(script)});
  return yandexMapsPromise;
}
function yandexWidgetMap(element,zoom,selectable){
  const center={lat:state.coords.lat,lng:state.coords.lng};
  const draw=()=>{element.innerHTML=`<iframe class="yandex-map-frame" title="Яндекс Карта" src="https://yandex.ru/map-widget/v1/?ll=${center.lng}%2C${center.lat}&z=${zoom}&l=map" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>${selectable?'<p class="map-fallback-note">Для точного выбора точки используйте геолокацию. Интерактивный выбор будет доступен после подключения ключа Яндекс Карт.</p>':''}`};draw();
  return {__selected:{...center},__radius:{setRadius(){}},setView(coords,nextZoom=zoom){center.lat=Number(coords[0]);center.lng=Number(coords[1]);zoom=nextZoom;this.__selected={...center};draw()},fire(type,payload){if(type==='click'&&payload?.latlng)this.__selected={lat:Number(payload.latlng.lat),lng:Number(payload.latlng.lng)}},getCenter(){return {...center}},remove(){element.replaceChildren()}};
}
async function initMap(id,items=[],selectable=false){
  const element=document.getElementById(id);if(!element)return;const existing=state.maps.get(id);if(existing)try{existing.remove()}catch{}
  const zoom=state.radius>150?6:state.radius>50?8:state.radius>15?10:12,ymaps=await loadYandexMaps();if(!document.body.contains(element))return;
  if(!ymaps){state.maps.set(id,yandexWidgetMap(element,zoom,selectable));return}
  const nativeMap=new ymaps.Map(element,{center:[state.coords.lat,state.coords.lng],zoom,controls:['zoomControl','geolocationControl']},{suppressMapOpenBlock:true});
  const radius=new ymaps.Circle([[state.coords.lat,state.coords.lng],state.radius*1000],{hintContent:'Радиус поиска'},{strokeColor:'#8f1d46',strokeWidth:2,fillColor:'#8f1d4618'});nativeMap.geoObjects.add(radius);
  nativeMap.geoObjects.add(new ymaps.Placemark([state.coords.lat,state.coords.lng],{hintContent:'Ваш центр поиска'},{preset:'islands#greenCircleDotIcon'}));
  items.forEach(item=>{const lat=Number(item.latitude),lng=Number(item.longitude);if(Number.isFinite(lat)&&Number.isFinite(lng))nativeMap.geoObjects.add(new ymaps.Placemark([lat,lng],{balloonContentHeader:escapeHtml(item.title),balloonContentBody:escapeHtml(item.subcategory||categoryLabel(item.category))},{preset:item.customer_id?'islands#blueCircleDotIcon':'islands#redCircleDotIcon'}))});
  let selected;const choose=coords=>{if(selected)nativeMap.geoObjects.remove(selected);selected=new ymaps.Placemark(coords,{}, {preset:'islands#redCircleDotIcon'});nativeMap.geoObjects.add(selected);adapter.__selected={lat:Number(coords[0]),lng:Number(coords[1])};nativeMap.panTo(coords)};
  const adapter={__selected:null,__radius:{setRadius(meters){radius.geometry.setRadius(meters)}},setView(coords,nextZoom=zoom){nativeMap.setCenter(coords,nextZoom)},fire(type,payload){if(type==='click'&&payload?.latlng)choose([payload.latlng.lat,payload.latlng.lng])},getCenter(){const point=nativeMap.getCenter();return{lat:Number(point[0]),lng:Number(point[1])}},remove(){nativeMap.destroy()}};
  if(selectable){nativeMap.events.add('click',event=>choose(event.get('coords')));choose([state.coords.lat,state.coords.lng])}state.maps.set(id,adapter);
}
function updateMapRadius(){for(const map of state.maps.values())if(map.__radius)map.__radius.setRadius(state.radius*1000)}

const cfg=window.POMOGAY_CONFIG||{};
const sb=window.supabase&&cfg.SUPABASE_URL&&cfg.SUPABASE_ANON_KEY?window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY,{auth:{flowType:'pkce',detectSessionInUrl:false,persistSession:true,autoRefreshToken:true}}):null;
function requireAuth(){if(!state.session){showAuth('login');toast('Сначала войдите или зарегистрируйтесь');return false}if(!validFullName(state.user.name)||!state.user.birth_date){editProfile();toast('Завершите профиль: укажите полное ФИО и дату рождения');return false}return true}
function isNativeApp(){return !!(window.Capacitor&&window.Capacitor.isNativePlatform&&window.Capacitor.isNativePlatform())}
function getAuthRedirectUrl(){return isNativeApp()?'pomogay://auth-callback':`${location.origin}${location.pathname}`}
let pendingSignup=null;
function showAuth(mode='login'){
  if(mode==='signup'){showSignupIdentity();return}
  modal(`<div class="auth-panel"><h2>Вход</h2><form class="auth-login-form" onsubmit="authSubmit(event)"><label class="auth-input"><span class="sr-only">Телефон или почта</span><input name="identity" required autocomplete="username" inputmode="email" placeholder="Телефон или почта"></label><label class="auth-input"><span class="sr-only">Пароль</span><input name="password" type="password" required autocomplete="current-password" placeholder="Пароль"></label><div class="auth-options"><label class="remember-password"><input name="remember" type="checkbox" checked><span>Запомнить пароль</span></label><button class="text-button" type="button" onclick="showPasswordReset()">Забыли пароль?</button></div><div id="authError" class="form-error" hidden></div><button class="primary-button auth-login-submit">Войти</button></form><section class="auth-alternatives"><p>Или продолжить через</p><div class="auth-provider-row"><button type="button" onclick="externalAuth('yandex')" aria-label="Продолжить через Яндекс"><span class="auth-provider yandex">Я</span><small>Яндекс</small></button><button type="button" onclick="externalAuth('gosuslugi')" aria-label="Продолжить через Госуслуги"><span class="auth-provider gosuslugi"><i></i></span><small>Госуслуги</small></button></div><p class="auth-signup-question">Нет аккаунта в Помогай?</p><button class="secondary-button auth-register-button" onclick="showAuth('signup')">Зарегистрироваться</button></section></div>`);
}
function showSignupIdentity(){
  pendingSignup=null;
  modal(`<div class="auth-panel signup-step"><button class="auth-step-back" type="button" onclick="showAuth('login')" aria-label="Вернуться ко входу">←</button><span class="auth-step-count">Шаг 1 из 2</span><h2>Регистрация</h2><p class="muted">Введите телефон или email. На него придёт подтверждение аккаунта.</p><form class="signup-step-form" onsubmit="continueSignupIdentity(event)"><label class="auth-input"><span class="sr-only">Телефон или email</span><input name="identity" required autocomplete="username" inputmode="email" placeholder="Телефон или email" autofocus></label><div class="form-error" hidden></div><button class="primary-button full" type="submit">Продолжить</button></form><div class="divider signup-divider"><span>или продолжить через</span></div><div class="auth-provider-row signup-providers"><button type="button" onclick="externalAuth('yandex')" aria-label="Зарегистрироваться через Яндекс"><span class="auth-provider yandex">Я</span><small>Яндекс</small></button><button type="button" onclick="externalAuth('gosuslugi')" aria-label="Зарегистрироваться через Госуслуги"><span class="auth-provider gosuslugi"><i></i></span><small>Госуслуги</small></button></div><p class="auth-signup-question">Уже есть аккаунт?</p><button class="text-button auth-back-login" onclick="showAuth('login')">Войти</button></div>`);
}
function credentialsForIdentity(identity,password){
  const value=String(identity||'').trim();
  if(value.includes('@'))return {email:value.toLowerCase(),password};
  let phone=value.replace(/[^\d+]/g,'');
  if(phone.startsWith('8')&&phone.replace(/\D/g,'').length===11)phone=`+7${phone.slice(1)}`;
  else if(!phone.startsWith('+')&&phone.replace(/\D/g,'').length===10)phone=`+7${phone}`;
  else if(!phone.startsWith('+'))phone=`+${phone}`;
  return {phone,password};
}
function continueSignupIdentity(event){
  event.preventDefault();const form=event.currentTarget,value=String(new FormData(form).get('identity')||'').trim(),credentials=credentialsForIdentity(value,'');
  if(credentials.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(credentials.email))return showFormError(form,'Введите корректный email.');
  if(credentials.phone){const digits=credentials.phone.replace(/\D/g,'');if(digits.length<10||digits.length>15)return showFormError(form,'Введите корректный номер телефона.');}
  pendingSignup={method:credentials.email?'email':'phone',credential:credentials.email||credentials.phone};showSignupPassword();
}
function showSignupPassword(){
  if(!pendingSignup){showSignupIdentity();return}
  modal(`<div class="auth-panel signup-step"><button class="auth-step-back" type="button" onclick="showSignupIdentity()" aria-label="Вернуться к телефону или email">←</button><span class="auth-step-count">Шаг 2 из 2</span><h2>Придумайте пароль</h2><p class="signup-identity-preview">${escapeHtml(pendingSignup.credential)}</p><form class="signup-step-form" onsubmit="submitSignupPassword(event)"><label class="auth-input"><span class="sr-only">Пароль</span><input name="password" type="password" minlength="8" required autocomplete="new-password" placeholder="Пароль" oninput="updatePasswordRules(this)"></label><ul class="password-rules" aria-live="polite"><li data-rule="length">Минимум 8 символов</li><li data-rule="letter">Хотя бы одна буква</li><li data-rule="number">Хотя бы одна цифра</li></ul><div class="form-error" hidden></div><button class="primary-button full signup-password-submit" type="submit" disabled>Продолжить</button></form></div>`);
}
function passwordIsValid(value){return String(value).length>=8&&/[A-Za-zА-Яа-яЁё]/.test(value)&&/\d/.test(value)}
function updatePasswordRules(input){
  const form=input.form,value=input.value,rules={length:value.length>=8,letter:/[A-Za-zА-Яа-яЁё]/.test(value),number:/\d/.test(value)};
  Object.entries(rules).forEach(([rule,valid])=>form.querySelector(`[data-rule="${rule}"]`)?.classList.toggle('valid',valid));form.querySelector('.signup-password-submit').disabled=!Object.values(rules).every(Boolean);
}
async function submitSignupPassword(event){
  event.preventDefault();const form=event.currentTarget,password=String(new FormData(form).get('password')||'');if(!pendingSignup)return showSignupIdentity();if(!passwordIsValid(password))return showFormError(form,'Пароль должен содержать минимум 8 символов, буквы и цифры.');if(!sb)return showFormError(form,'Не удалось подключиться к сервису аккаунтов.');setFormBusy(form,true);
  try{
    const credentials=pendingSignup.method==='email'?{email:pendingSignup.credential,password}:{phone:pendingSignup.credential,password},result=await sb.auth.signUp({...credentials,options:{emailRedirectTo:getAuthRedirectUrl()}});if(result.error)throw result.error;
    if(pendingSignup.method==='phone'){showPhoneVerification(pendingSignup.credential);return}
    if(result.data.session)await sb.auth.signOut();showEmailVerification(pendingSignup.credential);
  }catch(error){showFormError(form,friendlyAuthError(error))}finally{setFormBusy(form,false)}
}
async function authSubmit(event){
  event.preventDefault();if(!sb)return showFormError(event.currentTarget,'Не удалось подключиться к сервису аккаунтов.');const form=event.currentTarget,d=Object.fromEntries(new FormData(form)),credentials=credentialsForIdentity(d.identity,d.password);setFormBusy(form,true);
  try{const result=await sb.auth.signInWithPassword(credentials);if(result.error)throw result.error;state.session=result.data.session;await ensureProfile();closeModal();await loadCloud();render();toast('Вы вошли')}catch(error){showFormError(form,friendlyAuthError(error))}finally{setFormBusy(form,false)}
}
function showEmailVerification(email){modal(`<div class="auth-panel verification-step"><span class="verification-mark">✓</span><h2>Подтвердите email</h2><p>Мы отправили ссылку на <b>${escapeHtml(email)}</b>. Перейдите по ней, чтобы завершить регистрацию.</p><button class="primary-button full" onclick="showAuth('login')">Перейти ко входу</button></div>`)}
function showPhoneVerification(phone){modal(`<h2>Подтверждение телефона</h2><p class="muted">Введите код из SMS, отправленный на ${escapeHtml(phone)}.</p><form class="form-grid" onsubmit="verifyPhoneOtp(event,${arg(phone)})"><label class="field full-field"><span>Код из SMS</span><input name="token" inputmode="numeric" autocomplete="one-time-code" minlength="6" maxlength="8" required placeholder="000000"></label><div class="form-error full-field" hidden></div><button class="primary-button full-field">Подтвердить</button></form>`)}
async function verifyPhoneOtp(event,phone){event.preventDefault();const form=event.currentTarget,token=String(new FormData(form).get('token')||'').replace(/\D/g,'');setFormBusy(form,true);const result=await sb.auth.verifyOtp({phone,token,type:'sms'});setFormBusy(form,false);if(result.error)return showFormError(form,'Неверный или просроченный код.');state.session=result.data.session;await ensureProfile();closeModal();await loadCloud();render();toast('Телефон подтверждён')}
function externalAuth(provider){const label=provider==='yandex'?'Яндекс':'Госуслуги',url=provider==='yandex'?cfg.YANDEX_AUTH_URL:cfg.GOSUSLUGI_AUTH_URL;if(!url)return toast(`Вход через ${label} станет доступен после подключения провайдера`);location.assign(url)}
async function oauthSignIn(provider){if(!sb)return toast('Сервис входа недоступен');const result=await sb.auth.signInWithOAuth({provider,options:{redirectTo:getAuthRedirectUrl(),skipBrowserRedirect:isNativeApp()}});if(result.error)toast('Этот способ входа пока не включён администратором');else if(isNativeApp()&&result.data.url)location.href=result.data.url}
function showPasswordReset(){modal(`<h2>Восстановление пароля</h2><p class="muted">Отправим одноразовую безопасную ссылку на email аккаунта.</p><form class="form-grid" onsubmit="requestPasswordReset(event)"><label class="field full-field"><span>Email</span><input name="email" type="email" required autocomplete="email" inputmode="email" value="${escapeHtml(state.session?.user?.email||'')}" placeholder="name@example.com"></label><div class="form-error full-field" hidden></div><button class="primary-button full-field">Отправить ссылку</button></form>`)}
async function requestPasswordReset(event){event.preventDefault();if(!sb)return;const form=event.currentTarget,email=String(new FormData(form).get('email')||'').trim().toLowerCase();setFormBusy(form,true);const result=await sb.auth.resetPasswordForEmail(email,{redirectTo:getAuthRedirectUrl()});setFormBusy(form,false);if(result.error)return showFormError(form,'Не удалось отправить письмо. Проверьте адрес и попробуйте снова.');closeModal();toast('Ссылка для сброса пароля отправлена на email')}
function showNewPassword(){modal(`<h2>Новый пароль</h2><form class="form-grid" onsubmit="updatePassword(event)"><label class="field full-field"><span>Новый пароль</span><input name="password" type="password" minlength="12" required autocomplete="new-password" placeholder="Не менее 12 символов"></label><div class="form-error full-field" hidden></div><button class="primary-button full-field">Сохранить пароль</button></form>`)}
async function updatePassword(event){event.preventDefault();const form=event.currentTarget,password=new FormData(form).get('password'),result=await sb.auth.updateUser({password});if(result.error)return showFormError(form,'Не удалось изменить пароль.');closeModal();toast('Пароль изменён')}
function friendlyAuthError(error){const text=String(error?.message||'');if(text.includes('Invalid login credentials'))return'Неверный email или пароль.';if(text.includes('already registered'))return'Такой email уже зарегистрирован.';if(text.includes('Email not confirmed'))return'Сначала подтвердите email по ссылке из письма.';return'Не удалось выполнить вход. Попробуйте ещё раз.'}
function friendlyDatabaseError(error,fallback){const text=String(error?.message||'');if(text.includes('5 МБ')||text.includes('JPG'))return text;if(text.includes('verified identity'))return'Подтверждённые ФИО и дату рождения можно изменить только через поддержку.';return fallback}
function clearPrivateSessionState(){state.user={name:'',city:'Москва',verified:false};state.tasks=[];state.conversations=[];state.messages=[];state.people=[];state.favorites=[];state.activeConversation=null}
async function signOut(){try{if(sb)await sb.auth.signOut()}finally{closeModal();state.session=null;clearPrivateSessionState();state.page='home';render();toast('Вы вышли')}}

window.handleAuthDeepLink=async function(url){
  if(!sb||!url)return false;
  try{
    const parsed=new URL(url),trusted=isNativeApp()?parsed.protocol==='pomogay:'&&parsed.hostname==='auth-callback':parsed.origin===location.origin;if(!trusted)throw new Error('Untrusted auth callback URL');const query=parsed.searchParams,hash=new URLSearchParams((parsed.hash||'').replace(/^#/,'')),errorDescription=query.get('error_description')||hash.get('error_description');if(errorDescription)throw new Error(decodeURIComponent(errorDescription));const code=query.get('code');if(code){const result=await sb.auth.exchangeCodeForSession(code);if(result.error)throw result.error;state.session=result.data.session;await ensureProfile();closeModal();render();return true}const access_token=hash.get('access_token')||query.get('access_token'),refresh_token=hash.get('refresh_token')||query.get('refresh_token');if(access_token&&refresh_token){const result=await sb.auth.setSession({access_token,refresh_token});if(result.error)throw result.error;state.session=result.data.session;await ensureProfile();closeModal();render();return true}return false;
  }catch(error){console.warn('Auth callback error',error);toast('Не удалось завершить вход. Попробуйте ещё раз.');return false}
};

async function ensureProfile(){
  if(!sb||!state.session)return;const user=state.session.user,meta=user.user_metadata||{};let result=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(result.error)console.warn(result.error);let data=result.data;if(!data){const fallback={id:user.id,name:meta.name||user.email?.split('@')[0]||'Пользователь',city:meta.city||'Москва',avatar_url:meta.avatar_url||null},created=await sb.from('profiles').insert(fallback).select().single();if(!created.error)data=created.data}
  if(data){
    const privateResult=await sb.from('profile_private').select('birth_date,phone').eq('id',user.id).maybeSingle();
    const privateData=privateResult.error?{}:(privateResult.data||{});
    state.user={name:data.name||meta.name||'Пользователь',city:data.city||meta.city||'Москва',verified:!!data.verified,avatar_url:data.avatar_url||meta.avatar_url||null,birth_date:privateData.birth_date||meta.birth_date||'',phone:privateData.phone||'',bio:data.bio||'',languages:data.languages||'',experience_years:data.experience_years??''};
  }
}
function taskFromRow(row){return{...row,category:categoryId(row.category),subcategory:row.subcategory||''}}
async function loadCloud(){
  if(!sb)return;
  try{
    const services=await sb.from('services').select('*,profiles(name,rating,verified,avatar_url)').eq('is_active',true).order('created_at',{ascending:false});if(!services.error)state.services=[...(services.data||[]),...seedServices];
    const tasks=await sb.from('tasks').select('*').eq('status','open').order('created_at',{ascending:false});if(!tasks.error)state.tasks=(tasks.data||[]).map(taskFromRow);
    if(state.session){const favorites=await sb.from('favorites').select('service_id').eq('user_id',state.session.user.id);if(!favorites.error)state.favorites=(favorites.data||[]).map(item=>item.service_id);await loadConversations(false)}state.cloudReady=true;
  }catch(error){console.warn('Cloud load',error)}
}
async function loadConversations(shouldRender=true){
  if(!sb||!state.session)return;const uid=state.session.user.id,result=await sb.from('conversations').select('id,task_id,customer_id,helper_id,created_at,customer:profiles!conversations_customer_id_fkey(id,name,avatar_url),helper:profiles!conversations_helper_id_fkey(id,name,avatar_url),messages(id,body,sender_id,created_at,read_at)').or(`customer_id.eq.${uid},helper_id.eq.${uid}`).order('created_at',{ascending:false});if(result.error){console.warn(result.error);return}state.conversations=(result.data||[]).map(item=>({...item,lastMessage:[...(item.messages||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]||null})).sort((a,b)=>new Date(b.lastMessage?.created_at||b.created_at)-new Date(a.lastMessage?.created_at||a.created_at));if(shouldRender)render()}
function showLegal(kind){modal(`<h2>${kind==='privacy'?'Конфиденциальность':'Правила общения'}</h2><p class="muted">${kind==='privacy'?'Публично показываются только данные, нужные для выбора специалиста. Точный адрес задачи не должен отображаться до согласования с исполнителем.':'Не переводите предоплату незнакомым людям, не отправляйте документы в чате и фиксируйте условия задачи до начала работы.'}</p><button class="primary-button full" onclick="closeModal()">Понятно</button>`)}
function installHelp(){toast('Установите приложение через меню браузера «На экран Домой»')}
function render(){({home,catalog,create,chats,profile}[state.page]||home)()}

async function initApp(){
  Object.assign(window,{state,go,render,selectIntent,continueIntent,applyCategory,openCategory,showAllCategories,chooseSubcategory,setCatalogMode,setCategory,setSubcategory,setView,searchCatalog,showFilters,refreshFilterSubcategories,applyFilters,previewRadius,commitRadius,setCreateMode,updateCreateSubcategories,openAddressPicker,confirmAddress,publishTask,publishService,searchPeople,clearPeopleSearch,startDirectChat,openConversation,sendMessage,editProfile,saveProfile,verifyIdentity,showSafety,showAccountSettings,showSupport,showBonusShop,showPromotion,paymentUnavailable,openService,contactService,toggleFavorite,respondToTask,reportUser,showLocationMenu,chooseCity,setCity,useMyLocation,closeModal,showAuth,showSignupIdentity,continueSignupIdentity,showSignupPassword,updatePasswordRules,submitSignupPassword,authSubmit,oauthSignIn,requestPasswordReset,updatePassword,signOut,showLegal,installHelp});
  render();if(!sb){toast('Не удалось подключиться к Supabase');return}const session=await sb.auth.getSession();state.session=session.data.session;if(location.search.includes('code=')||location.hash.includes('access_token=')){await window.handleAuthDeepLink(location.href);history.replaceState({},document.title,location.pathname)}await ensureProfile();await loadCloud();render();sb.auth.onAuthStateChange(async(event,sessionValue)=>{state.session=sessionValue;if(event==='PASSWORD_RECOVERY')showNewPassword();if(!sessionValue)clearPrivateSessionState();await ensureProfile();await loadCloud();render()});if('serviceWorker'in navigator&&!isNativeApp())navigator.serviceWorker.register('sw.js')
}
initApp();
